### ISSUE TITLE
Failed error connection refused

### ISSUE THREAD

**Issue by macbroadcast** [simpulton/simple-rest-website#1]
Sorry i am new to angular, I just came across your exellent example and set both up ,but when i want to connect from this example to the API is gives me an error in the javascript console: 'Failed to load resource: net::ERR_CONNECTION_REFUSED'

what paramenters i need to change to make it work :)

Thanks a lot

**Comment by sathvikareddyk** [comment]
can any1 help me in solving this

[http://localhost:4201/r
![Screenshot (68)](https://user-images.githubusercontent.com/66214464/89101359-c7886900-d41c-11ea-8635-0b4e6f5b12c7.png)
egister](url)
